### ISSUE TITLE
Metadata are not all updated to OEP-1.4.0

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/open-MaStR#43] opened 2019-10-22 08:38 UTC
OEP-1.4.0 [template](https://github.com/OpenEnergyPlatform/examples/blob/master/metadata/oep_metadata_template.json#L80)

**Comment by Ludee** [comment] 2019-11-28 16:17
Is a duplicate of #19

**Closed as completed by Ludee** 2019-11-28 16:17 UTC
Labels: duplicate
